// <auto-generated />
using System;
using IdentityExtension.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityExtension.Migrations.DnlDB
{
    [DbContext(typeof(DnlDBContext))]
    [Migration("20220715105846_updatednl")]
    partial class updatednl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityExtension.Models.Ais", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("antennaHeight");

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("freqBand");

                    b.Property<string>("location");

                    b.Property<string>("maxDetectRange");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("powerOp");

                    b.Property<string>("price");

                    b.Property<string>("security");

                    b.Property<string>("type");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("ais");
                });

            modelBuilder.Entity("IdentityExtension.Models.Ammunition", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("ammunitions");
                });

            modelBuilder.Entity("IdentityExtension.Models.Anemometers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<string>("outputPower");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("anemometers");
                });

            modelBuilder.Entity("IdentityExtension.Models.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("code");

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("areas");
                });

            modelBuilder.Entity("IdentityExtension.Models.Base", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("areaId");

                    b.Property<int>("baseType");

                    b.Property<int>("code");

                    b.Property<string>("description");

                    b.Property<string>("payBase");

                    b.Property<string>("remCd");

                    b.Property<int>("shipTypeId");

                    b.HasKey("id");

                    b.HasIndex("areaId");

                    b.HasIndex("shipTypeId");

                    b.ToTable("bases");
                });

            modelBuilder.Entity("IdentityExtension.Models.CanonType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("canonTypes");
                });

            modelBuilder.Entity("IdentityExtension.Models.CCTV", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("channels");

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<string>("noOfCameras");

                    b.Property<string>("noOfDisplays");

                    b.Property<string>("noOfHdd");

                    b.Property<string>("systemId");

                    b.Property<string>("systemType");

                    b.Property<string>("typeOfCameras");

                    b.Property<string>("typeOfDisplays");

                    b.Property<string>("typeOfHdd");

                    b.Property<string>("typeOfPeriod");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("cCTVs");
                });

            modelBuilder.Entity("IdentityExtension.Models.Communication", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("freqBand");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("powerOp");

                    b.Property<string>("price");

                    b.Property<string>("security");

                    b.Property<string>("type");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("communications");
                });

            modelBuilder.Entity("IdentityExtension.Models.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("IdentityExtension.Models.DVR", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<string>("dvrSubmitMake");

                    b.Property<string>("dvrSubmitModel");

                    b.Property<string>("dvrSubmitSrno");

                    b.Property<string>("dvrSubmitState");

                    b.Property<string>("dvrSubmitType");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("dVRs");
                });

            modelBuilder.Entity("IdentityExtension.Models.ECDI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("eCDIs");
                });

            modelBuilder.Entity("IdentityExtension.Models.Engine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("equipId");

                    b.Property<string>("powerRating");

                    b.Property<DateTime?>("proFileDate");

                    b.Property<DateTime?>("warrantyDate");

                    b.HasKey("id");

                    b.HasIndex("equipId")
                        .IsUnique();

                    b.ToTable("engines");
                });

            modelBuilder.Entity("IdentityExtension.Models.EODs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("country");

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<string>("pulseCount");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("eODs");
                });

            modelBuilder.Entity("IdentityExtension.Models.Epirb", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("batteryExpDate");

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<DateTime?>("hruRepDate");

                    b.Property<string>("location");

                    b.Property<string>("mmsiReg");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("epirbs");
                });

            modelBuilder.Entity("IdentityExtension.Models.Equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("action");

                    b.Property<DateTime?>("cDate");

                    b.Property<string>("del");

                    b.Property<DateTime?>("delDate");

                    b.Property<int>("eqBase");

                    b.Property<int>("eqTId");

                    b.Property<DateTime?>("g47Date");

                    b.Property<string>("g47Remarks");

                    b.Property<string>("make");

                    b.Property<string>("model");

                    b.Property<string>("remarks");

                    b.Property<string>("srNo")
                        .IsRequired();

                    b.Property<string>("state");

                    b.Property<string>("userId");

                    b.HasKey("id");

                    b.HasIndex("eqBase");

                    b.HasIndex("eqTId");

                    b.ToTable("equipments");
                });

            modelBuilder.Entity("IdentityExtension.Models.EquipmentProcurement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fileRef");

                    b.Property<string>("item");

                    b.Property<string>("proDistribution");

                    b.Property<int>("procuId");

                    b.HasKey("id");

                    b.HasIndex("procuId")
                        .IsUnique();

                    b.ToTable("equipmentProcurements");
                });

            modelBuilder.Entity("IdentityExtension.Models.EquipmentTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("equipment")
                        .IsRequired();

                    b.Property<int>("equipmentCode");

                    b.Property<string>("equipmentGeneralInq");

                    b.Property<string>("equipmentSellCode");

                    b.Property<string>("imageUrl");

                    b.Property<string>("varName")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("equipment_Tables");
                });

            modelBuilder.Entity("IdentityExtension.Models.EquipProcuView", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("cDate");

                    b.Property<int>("equipCode");

                    b.Property<string>("fileRef");

                    b.Property<string>("item");

                    b.Property<string>("lastPurchasePrice");

                    b.Property<string>("make");

                    b.Property<string>("model");

                    b.Property<string>("proDistribution");

                    b.Property<string>("qtyApproved");

                    b.Property<string>("qtyOrdered");

                    b.Property<string>("remarks");

                    b.Property<string>("rlRef");

                    b.Property<string>("userId");

                    b.HasKey("id");

                    b.ToTable("EquipProcuView");
                });

            modelBuilder.Entity("IdentityExtension.Models.Generator", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("alternatorMake");

                    b.Property<string>("alternatorModel");

                    b.Property<string>("alternatorSrno");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("frequancy");

                    b.Property<string>("fullLoad");

                    b.Property<string>("kva");

                    b.Property<string>("ledgerPageNo");

                    b.Property<string>("maxLoad");

                    b.Property<string>("mode");

                    b.Property<string>("mountedAt");

                    b.Property<string>("mrh");

                    b.Property<string>("phase");

                    b.Property<string>("presentage");

                    b.Property<string>("primemoverMake");

                    b.Property<string>("primemoverModel");

                    b.Property<string>("primemoverSrno");

                    b.Property<string>("totalRunHours");

                    b.Property<string>("voltage");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("generators");
                });

            modelBuilder.Entity("IdentityExtension.Models.Gps", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("gps");
                });

            modelBuilder.Entity("IdentityExtension.Models.Guncom", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("guncoms");
                });

            modelBuilder.Entity("IdentityExtension.Models.Gyro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("interfaceUsed");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("gyros");
                });

            modelBuilder.Entity("IdentityExtension.Models.IntegratedHeadingSensor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("interfaceUsed");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("integratedHeadingSensors");
                });

            modelBuilder.Entity("IdentityExtension.Models.Make", b =>
                {
                    b.Property<int>("makeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description");

                    b.HasKey("makeId");

                    b.ToTable("Makes");
                });

            modelBuilder.Entity("IdentityExtension.Models.MakeModel", b =>
                {
                    b.Property<int>("makeId");

                    b.Property<int>("modelId");

                    b.Property<int>("eqTId");

                    b.Property<int>("id");

                    b.Property<string>("system");

                    b.HasKey("makeId", "modelId");

                    b.HasAlternateKey("id");

                    b.HasIndex("eqTId");

                    b.HasIndex("modelId");

                    b.ToTable("MakeModels");
                });

            modelBuilder.Entity("IdentityExtension.Models.MiniSat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("miniSats");
                });

            modelBuilder.Entity("IdentityExtension.Models.Model", b =>
                {
                    b.Property<int>("modelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description");

                    b.HasKey("modelId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("IdentityExtension.Models.Navtex", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("navtexs");
                });

            modelBuilder.Entity("IdentityExtension.Models.Procurement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("cDate");

                    b.Property<int>("equipCode");

                    b.Property<string>("lastPurchasePrice");

                    b.Property<string>("make");

                    b.Property<string>("model");

                    b.Property<string>("qtyApproved");

                    b.Property<string>("qtyOrdered");

                    b.Property<string>("remarks");

                    b.Property<string>("rlRef");

                    b.Property<string>("userId");

                    b.HasKey("id");

                    b.HasIndex("equipCode");

                    b.ToTable("procurements");
                });

            modelBuilder.Entity("IdentityExtension.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.Property<string>("type");

                    b.HasKey("productId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("IdentityExtension.Models.Radar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<string>("dingyRange");

                    b.Property<int>("eqId");

                    b.Property<string>("facRange");

                    b.Property<string>("fgbRange");

                    b.Property<string>("ipcRange");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("power");

                    b.Property<string>("price");

                    b.Property<string>("runningHours");

                    b.Property<string>("scannerLength");

                    b.Property<string>("supply");

                    b.Property<string>("trawlerRange");

                    b.Property<string>("voltage");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("radars");
                });

            modelBuilder.Entity("IdentityExtension.Models.Sart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<string>("outputPower");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("sarts");
                });

            modelBuilder.Entity("IdentityExtension.Models.SatCompass", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("satCompasses");
                });

            modelBuilder.Entity("IdentityExtension.Models.SatPhone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("antennaSrno");

                    b.Property<string>("dataLimit");

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<string>("email");

                    b.Property<int>("eqId");

                    b.Property<DateTime?>("expireDateBattery");

                    b.Property<string>("fax");

                    b.Property<string>("imeNo");

                    b.Property<string>("inSNo");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<string>("receiverSrno");

                    b.Property<string>("type");

                    b.Property<string>("voice");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("satPhones");
                });

            modelBuilder.Entity("IdentityExtension.Models.ShipType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("code");

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("ShipType");
                });

            modelBuilder.Entity("IdentityExtension.Models.Sonar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<string>("typeOfTransducer");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("sonars");
                });

            modelBuilder.Entity("IdentityExtension.Models.SpareProcurement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("currentStock");

                    b.Property<string>("firstRate");

                    b.Property<string>("forthRate");

                    b.Property<string>("partNo");

                    b.Property<int>("procuId");

                    b.Property<string>("sbRef");

                    b.Property<string>("secondRate");

                    b.Property<string>("thirdRate");

                    b.HasKey("id");

                    b.HasIndex("procuId")
                        .IsUnique();

                    b.ToTable("spareProcurements");
                });

            modelBuilder.Entity("IdentityExtension.Models.SpareProcuView", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("cDate");

                    b.Property<string>("currentStock");

                    b.Property<int>("equipCode");

                    b.Property<string>("firstRate");

                    b.Property<string>("forthRate");

                    b.Property<string>("lastPurchasePrice");

                    b.Property<string>("make");

                    b.Property<string>("model");

                    b.Property<string>("partNo");

                    b.Property<int>("procuId");

                    b.Property<string>("qtyApproved");

                    b.Property<string>("qtyOrdered");

                    b.Property<string>("remarks");

                    b.Property<string>("rlRef");

                    b.Property<string>("sbRef");

                    b.Property<string>("secondRate");

                    b.Property<string>("thirdRate");

                    b.Property<string>("userId");

                    b.HasKey("id");

                    b.ToTable("SpareProcuView");
                });

            modelBuilder.Entity("IdentityExtension.Models.speedLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<string>("outputPower");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("speedLogs");
                });

            modelBuilder.Entity("IdentityExtension.Models.SubUnit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("baseId");

                    b.Property<string>("description");

                    b.Property<int>("subUnitCode");

                    b.Property<int>("type");

                    b.HasKey("id");

                    b.HasIndex("baseId");

                    b.ToTable("subUnits");
                });

            modelBuilder.Entity("IdentityExtension.Models.Weapon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Ammunitionid");

                    b.Property<int?>("CanonTypeid");

                    b.Property<int?>("Countryid");

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<string>("outputPower");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("Ammunitionid");

                    b.HasIndex("CanonTypeid");

                    b.HasIndex("Countryid");

                    b.HasIndex("eqId");

                    b.ToTable("weapons");
                });

            modelBuilder.Entity("IdentityExtension.Models.XenonSLight", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dateInstalled");

                    b.Property<DateTime?>("dateModified");

                    b.Property<int>("eqId");

                    b.Property<string>("location");

                    b.Property<string>("outputPower");

                    b.Property<DateTime?>("pfileDate");

                    b.Property<string>("pfileNum");

                    b.Property<string>("price");

                    b.Property<DateTime?>("weDate");

                    b.HasKey("id");

                    b.HasIndex("eqId");

                    b.ToTable("xenonS");
                });

            modelBuilder.Entity("IdentityExtension.Models.Ais", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Anemometers", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Base", b =>
                {
                    b.HasOne("IdentityExtension.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("areaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IdentityExtension.Models.ShipType", "ShipType")
                        .WithMany("Base")
                        .HasForeignKey("shipTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.CCTV", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Communication", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.DVR", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.ECDI", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Engine", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithOne("Engine")
                        .HasForeignKey("IdentityExtension.Models.Engine", "equipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.EODs", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Epirb", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Equipment", b =>
                {
                    b.HasOne("IdentityExtension.Models.Base", "Base")
                        .WithMany()
                        .HasForeignKey("eqBase")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IdentityExtension.Models.EquipmentTable", "EquipmentTable")
                        .WithMany("Equipment")
                        .HasForeignKey("eqTId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.EquipmentProcurement", b =>
                {
                    b.HasOne("IdentityExtension.Models.Procurement", "Procurement")
                        .WithOne("EquipmentProcurement")
                        .HasForeignKey("IdentityExtension.Models.EquipmentProcurement", "procuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Generator", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Gps", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Guncom", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Gyro", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.IntegratedHeadingSensor", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.MakeModel", b =>
                {
                    b.HasOne("IdentityExtension.Models.EquipmentTable", "EquipmentTable")
                        .WithMany("MakeModels")
                        .HasForeignKey("eqTId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IdentityExtension.Models.Make", "Make")
                        .WithMany()
                        .HasForeignKey("makeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IdentityExtension.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("modelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.MiniSat", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Navtex", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Procurement", b =>
                {
                    b.HasOne("IdentityExtension.Models.EquipmentTable", "EquipmentTable")
                        .WithMany("Procurements")
                        .HasForeignKey("equipCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Radar", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Sart", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.SatCompass", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.SatPhone", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Sonar", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.SpareProcurement", b =>
                {
                    b.HasOne("IdentityExtension.Models.Procurement", "Procurement")
                        .WithOne("SpareProcurement")
                        .HasForeignKey("IdentityExtension.Models.SpareProcurement", "procuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.speedLog", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.SubUnit", b =>
                {
                    b.HasOne("IdentityExtension.Models.Base", "Base")
                        .WithMany("SubUnits")
                        .HasForeignKey("baseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.Weapon", b =>
                {
                    b.HasOne("IdentityExtension.Models.Ammunition", "Ammunition")
                        .WithMany("Weapon")
                        .HasForeignKey("Ammunitionid");

                    b.HasOne("IdentityExtension.Models.CanonType", "CanonType")
                        .WithMany("Weapon")
                        .HasForeignKey("CanonTypeid");

                    b.HasOne("IdentityExtension.Models.Country", "Country")
                        .WithMany("Weapon")
                        .HasForeignKey("Countryid");

                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdentityExtension.Models.XenonSLight", b =>
                {
                    b.HasOne("IdentityExtension.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("eqId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
