// <auto-generated />
using System;
using IdentityExtension.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityExtension.Migrations
{
    [DbContext(typeof(DnlDBContext))]
    [Migration("20220613050444_dnls")]
    partial class dnls
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityExtension.Models.EquipmentProcurement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fileRef");

                    b.Property<string>("item");

                    b.Property<string>("proDistribution");

                    b.Property<int>("procuId");

                    b.HasKey("id");

                    b.HasIndex("procuId")
                        .IsUnique();

                    b.ToTable("equipmentProcurements");
                });

            modelBuilder.Entity("IdentityExtension.Models.EquipmentTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("equipment")
                        .IsRequired();

                    b.Property<int>("equipmentCode");

                    b.Property<string>("equipmentGeneralInq");

                    b.Property<string>("equipmentSellCode");

                    b.Property<string>("imageUrl");

                    b.HasKey("id");

                    b.ToTable("equipment_Tables");
                });

            modelBuilder.Entity("IdentityExtension.Models.Procurement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("cDate");

                    b.Property<string>("equipCode");

                    b.Property<string>("lastPurchasePrice");

                    b.Property<string>("make");

                    b.Property<string>("model");

                    b.Property<string>("qtyApproved");

                    b.Property<string>("qtyOrdered");

                    b.Property<string>("remarks");

                    b.Property<string>("rlRef");

                    b.Property<string>("userId");

                    b.HasKey("id");

                    b.ToTable("procurements");
                });

            modelBuilder.Entity("IdentityExtension.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.Property<string>("type");

                    b.HasKey("productId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("IdentityExtension.Models.EquipmentProcurement", b =>
                {
                    b.HasOne("IdentityExtension.Models.Procurement", "Procurement")
                        .WithOne("EquipmentProcurement")
                        .HasForeignKey("IdentityExtension.Models.EquipmentProcurement", "procuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
